checks:
    php:
        code_rating: true
        duplication: true

tools:
    php_mess_detector: true
    php_code_sniffer: true
    sensiolabs_security_checker: true
    php_cpd: true
    php_loc: true
    php_pdepend: true
filter:
    paths:
        - src/*
build:
    nodes:
        analysis:
            environment:
                php:
                    version: 8.2
            tests:
                override:
                    - php-scrutinizer-run
                    - phpcs-run
